version: "3.8"
services:
  telemetry_generator:
    build: Telemetry
    image: oc/telemetrygenerator
    command: generate
    ports: 
      - 8000:8000
      - 8001:8001

  telemetry_string_receiver:
    build: TelemetryReceiver
    image: oc/telemetryreceiver
    command: string
    network_mode: host
    depends_on: 
      - telemetry_generator

  telemetry_binary_receiver:
    build: TelemetryReceiver
    image: oc/telemetryreceiver
    command: binary
    network_mode: host
    depends_on: 
      - telemetry_generator