apiVersion: influxdata.com/v2alpha1
kind: Label
metadata:
    name: busy-noyce-a1a001
spec:
    color: '#6BDFFF'
    name: DeadmanCheck
---
apiVersion: influxdata.com/v2alpha1
kind: Bucket
metadata:
    name: vigilant-bouman-a1a003
spec:
    name: telemetry
---
apiVersion: influxdata.com/v2alpha1
kind: CheckDeadman
metadata:
    name: agreeing-ptolemy-a1a007
spec:
    associations:
      - kind: Label
        name: busy-noyce-a1a001
    every: 1m0s
    level: CRIT
    name: Telemetry Status
    query: |-
        from(bucket: "telemetry")
          |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
          |> filter(fn: (r) => r["_measurement"] == "mem")
          |> filter(fn: (r) => r["_field"] == "value")
    staleTime: 10m0s
    status: active
    statusMessageTemplate: ${r._level}
    timeSince: 1m30s
---
apiVersion: influxdata.com/v2alpha1
kind: Dashboard
metadata:
    name: spectacular-blackwell-21a001
spec:
    charts:
      - axes:
          - base: "10"
            name: x
            scale: linear
          - label: Data Value
            name: y
            scale: linear
        colors:
          - hex: '#8F8AF4'
            id: 4436cfd1-4efe-4bbc-8be1-51500b35c773
            name: Do Androids Dream of Electric Sheep?
            type: scale
          - hex: '#A51414'
            id: 2ce58b46-e90a-45d1-912a-466f71a3a520
            name: Do Androids Dream of Electric Sheep?
            type: scale
          - hex: '#F4CF31'
            id: c8bffeca-49d6-4388-b36d-e08b04914457
            name: Do Androids Dream of Electric Sheep?
            type: scale
        geom: line
        height: 4
        kind: Xy
        name: Telemetry Graph
        position: overlaid
        queries:
          - query: |-
                from(bucket: "telemetry")
                  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
                  |> filter(fn: (r) => r["_measurement"] == "mem")
                  |> filter(fn: (r) => r["_field"] == "value")
                  |> aggregateWindow(every: 5s, fn: mean, createEmpty: false)
                  |> yield(name: "mean")
        shade: true
        width: 6
        xCol: _time
        yCol: _value
      - axes:
          - label: Value
            name: x
        colors:
          - hex: '#8F8AF4'
            id: 4436cfd1-4efe-4bbc-8be1-51500b35c773
            name: Do Androids Dream of Electric Sheep?
            type: scale
          - hex: '#A51414'
            id: 2ce58b46-e90a-45d1-912a-466f71a3a520
            name: Do Androids Dream of Electric Sheep?
            type: scale
          - hex: '#F4CF31'
            id: c8bffeca-49d6-4388-b36d-e08b04914457
            name: Do Androids Dream of Electric Sheep?
            type: scale
        fillColumns:
          - _start
          - _stop
          - _field
          - _measurement
          - host
        height: 5
        kind: Histogram
        name: Telemetry Histogram
        position: overlaid
        queries:
          - query: |-
                from(bucket: "telemetry")
                  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
                  |> filter(fn: (r) => r["_measurement"] == "mem")
                  |> filter(fn: (r) => r["_field"] == "value")
                  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
                  |> yield(name: "mean")
        width: 6
        xCol: _value
        yPos: 4
      - colors:
          - hex: '#9394FF'
            id: base
            name: comet
            type: text
        decimalPlaces: 2
        height: 1
        kind: Single_Stat
        name: String Encoded Satellite (ID01)
        queries:
          - query: |-
                from(bucket: "telemetry")
                  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
                  |> filter(fn: (r) => r["_measurement"] == "mem")
                  |> filter(fn: (r) => r["_field"] == "value")
                  |> filter(fn: (r) => r["host"] == "string_sat-ID01")
                  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)
                  |> yield(name: "last")
        width: 3
        xPos: 6
      - colors:
          - hex: '#ffffff'
            id: base
            name: white
            type: text
        decimalPlaces: 6
        fieldOptions:
          - displayName: _start
            fieldName: _start
          - displayName: _stop
            fieldName: _stop
          - displayName: Timestamp
            fieldName: _time
            visible: true
          - displayName: Satellite + ID
            fieldName: host
          - displayName: Value
            fieldName: _value
            visible: true
          - displayName: _field
            fieldName: _field
          - displayName: _measurement
            fieldName: _measurement
        height: 8
        kind: Table
        name: Telemetry Table
        queries:
          - query: |-
                from(bucket: "telemetry")
                  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
                  |> filter(fn: (r) => r["_measurement"] == "mem")
                  |> filter(fn: (r) => r["_field"] == "value")
                  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)
                  |> yield(name: "mean")
        tableOptions:
            sortBy: _time
            verticalTimeAxis: true
        timeFormat: YYYY-MM-DD HH:mm:ss
        width: 6
        xPos: 6
        yPos: 1
      - colors:
          - hex: '#9394FF'
            id: base
            name: comet
            type: text
        decimalPlaces: 2
        height: 1
        kind: Single_Stat
        name: Binary Encoded Satellite (ID02)
        queries:
          - query: |-
                from(bucket: "telemetry")
                  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
                  |> filter(fn: (r) => r["_measurement"] == "mem")
                  |> filter(fn: (r) => r["_field"] == "value")
                  |> filter(fn: (r) => r["host"] == "binary_sat-ID02")
                  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)
                  |> yield(name: "last")
        width: 3
        xPos: 9
    description: Dashboard displaying both a summary and the individual values available
        from each satellite
    name: Satellite Telemetry
